name: macos

on:
  push:
    branches: [ main, release/*, feature/* ]
  pull_request:
    branches: [ main, release/* ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Brew-Nats
      run: brew install nats-server
    - name: Run-Nats
      run: nats-server -DVV &
    - name: Run tests
      run: sleep 5 && swift test -v
